name: Update Index and Trigger Build

on:
  push:
    paths:
      - 'Cybersecurity/**'
      - 'LLM Security/**'

jobs:
  update-index-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update index.html
        run: |
          python update_index.py

      - name: Commit Changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m "Update index.html with new files"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/sivolko/mindmaps.git
          git push

      - name: Trigger Build
        run: |
          # Add commands to trigger your build process here
          echo "Build process triggered"
